export {default as category10} from "./src/category10";
export {default as category20b} from "./src/category20b";
export {default as category20c} from "./src/category20c";
export {default as category20} from "./src/category20";
export {default as cubehelix} from "./src/cubehelix";
export {default as identity} from "./src/identity";
export {default as linear} from "./src/linear";
export {default as log} from "./src/log";
export {default as ordinal} from "./src/ordinal";
export {default as pow, sqrt} from "./src/pow";
export {default as quantile} from "./src/quantile";
export {default as quantize} from "./src/quantize";
export {default as rainbow} from "./src/rainbow";
export {default as threshold} from "./src/threshold";
export {default as time} from "./src/time";
export {default as utcTime} from "./src/utcTime";
